### ISSUE TITLE
Android 4.1.2 - All menu items left-justified

### ISSUE THREAD

**Issue by spriggsha** [Financial-Times/o-header#82] opened 2014-09-03 10:06 UTC
Not sure if this is related to any previously-opened issues.

![image](https://cloud.githubusercontent.com/assets/7458891/4132481/fd1cd6a4-3351-11e4-914c-5bd882bf7ebf.png)

Produced the error on:
device_model = Sony SGP321
device_res = 1200x1848
orientation = portrait
os_name = Android
os_version = 4.1.2
pixel_density = 240 dpi
request_id = 90f9b9af-7381-47d8-9f50-1cff786b833f
status = Viewport
url = http://ft.com/fastft

**Comment by kaelig** [comment] 2015-04-06 16:44
Couldn't reproduce in v3.0.0. Closing.

**Closed by kaelig** 2015-04-06 16:44 UTC
