### ISSUE TITLE
Change styling and behaviour of edition switcher to improve usability issues

### ISSUE THREAD

**Issue by knicolai-git** [Financial-Times/o-header#202] opened 2016-07-29 13:35 UTC
Fixing an issue to make clear which edition is active and what's the clickable alternative.
Please include the following changes to style and behaviour:

- Active state: Metric, Semibold, #505050, 
- The active edition should be not clickable, this means it has also no hover-state
- Alternative options: Metric, Regular, #27757B, Underline

![new-edition-switcher](https://cloud.githubusercontent.com/assets/6247945/17249630/bcf8b1e0-5598-11e6-9244-1c7434aa18a9.png)

**Comment by pauloneillft** [comment] 2016-08-09 02:32
sticking my oar in... should this follow a standard origami toggle button UI?

**Comment by onishiweb** [comment] 2016-08-09 08:38
Duplicate of #201

**Closed** 2016-08-09 08:38 UTC

**Comment by i-like-robots** [comment] 2016-08-09 14:03
A little late to the party but here are some selected/non-selected links elsewhere in the navigation:

![screen shot 2016-08-09 at 15 01 31](https://cloud.githubusercontent.com/assets/271645/17519053/401af090-5e42-11e6-8823-a22e8bfa18e6.png)

So this appears to be the opposite of that - is this confusing too?

**Comment by AlbertoElias** [comment] 2016-08-09 15:50
@knicolai-git what do you think?
